name: Go Build and Release (Multi-Arch)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

- name: Build (multi-arch, static)
  run: |
    mkdir -p dist
    CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -v -o dist/moggio-windows-amd64.exe .
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o dist/moggio-linux-amd64 .
    CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=7 go build -v -o dist/moggio-linux-armv7 .
    CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -v -o dist/moggio-linux-arm64 .

      - name: Archive binaries
        uses: actions/upload-artifact@v4
        with:
          name: moggio-binaries
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: moggio-binaries
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
