name: Go Build and Release (ARM64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build (linux/arm64)
        run: |
          GOOS=linux GOARCH=arm64 go build -v -o moggio-linux-arm64 .

      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: moggio-linux-arm64
          path: moggio-linux-arm64

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: moggio-linux-arm64

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: moggio-linux-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
